runtime: nodejs
env: standard

# Optional: Define environment variables here
env_variables:
  NODE_ENV: 'production'

# Optional: Define automatic scaling settings
automatic_scaling:
  min_instances: 1
  max_instances: 10

# Optional: If you need specific instance class
instance_class: F2

# Optional: Define the health check
health_check:
  enable_health_check: True
  healthy_threshold: 3
  unhealthy_threshold: 3
  check_interval_sec: 5
  timeout_sec: 4
